# This is a basic workflow to help you get started with Actions

name: Build Wheels

on:
  push:
  create:
    tags: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Get Dependencies
        run: pip install twine build

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_SKIP: "*-win32 *-manylinux_i686"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Upload with twine
        run: |
          python -m pip install twine
          python -m twine upload wheelhouse/*.whl --skip-existing
        continue-on-error: true
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
